#####################################################################
# eNB1 Configuration - TAC 1 - HANDOVER ENABLED
# F2G Handover S1 + VoLTE Demo
#####################################################################

[enb]
enb_id = 0x19B
mcc = 001
mnc = 01
mme_addr = 192.168.1.102
gtp_bind_addr = 192.168.1.100
s1c_bind_addr = 192.168.1.100
s1c_bind_port = 0
n_prb = 50

[enb_files]
sib_config = /etc/srsran/sib.conf
rr_config = /tmp/rr_enb1_ho.conf
rb_config = /etc/srsran/rb.conf

[rf]
dl_earfcn = 1450
tx_gain = 80
rx_gain = 40
device_name = bladeRF
device_args = 
time_adv_nsamples = 27

[pcap]
enable = true
filename = /tmp/enb1_ho.pcap
s1ap_enable = true
s1ap_filename = /tmp/enb1_s1ap_ho.pcap

[log]
all_level = info
all_hex_limit = 32
filename = /tmp/enb1_ho.log

[expert]
nof_phy_threads = 3
metrics_period_secs = 1
tx_amplitude = 0.6
rrc_inactivity_timer = 60000
